version: '3'
services:
    web:
        image: hetzer
        ports:
            - "8000:8000"
        depends_on:
            - "mongo"
    mongo:
        image: "mongo:3.0.15"
    redis:
        image: "redis:3.2.11"
