name: hetzer
version: 0.1.0

dependencies:
    - base
    - bytestring
    - monad-control
    - mtl
    - snap-core
    - snap-server
    - snap
    - mongoDB
    - text
    - aeson
    - uuid
    - random
    - either-unwrap
    - regex-tdfa
    - transformers
    - bcrypt
    - hedis
    - jose
    - io-streams

executables:
    hetzer:
        source-dirs: src
        main: Main.hs
        exposed-modules: User

tests:
    spec:
        main: Spec.hs
        source-dirs:
            - test
            - src
        dependencies: hspec
